spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://ec2-23-21-129-125.compute-1.amazonaws.com:5432/d2b9hl5rvllubs
    username: hoizfkboifmoes
    password: 264185c6ff383ab7d29d2e633b01e4b0b519977e31423bb73144dab7408257c7
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql

  jackson:
    time-zone: America/Sao_Paulo

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob.non_contextual_creation: true

security:
  basic:
    enable: false
  oauth2:
    resource:
      filter-order: 3

oauth-clients:
  vendas_analytics:
    client: vendas_analytics-client
    secret: vendas_analytics-secret