spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://sqlvhnegrisoli.ddns.net:5432/vendas_analytics
    #url: jdbc:postgresql://localhost:5432/nutricao_esportiva
    username: postgres
    password: 1y5h8j
    initialization-mode: always
    initialize: true
    continue-on-error: true

  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob.non_contextual_creation: true

security:
  basic:
    enable: false
  oauth2:
    resource:
      filter-order: 3

oauth-clients:
  vendas_analytics:
    client: vendas_analytics-client
    secret: vendas_analytics-secret